### ISSUE TITLE
Create mock data generator endpoint

### ISSUE THREAD

**Issue by andras-adam** [tamaskr/crowdsourced-network-metrics#19]
Create a Cloud Function that
- Can be called via an HTTP request to `/generate` ([docs](https://cloud.google.com/functions/docs/writing/write-http-functions))
- Utilizes the script from #18 to generate mock measurements
- Can take a query parameter named `count` and will generate this many mock measurements (or e.g. 10 if no `count` is provided)
- Batch writes the generated mock measurements to the Firestore collection from #20 ([firestore docs](https://firebase.google.com/docs/firestore), [batch writes](https://firebase.google.com/docs/firestore/manage-data/transactions#batched-writes))
- Will respond with an HTTP status code of `200`, or `500` if an error has occured

**Definition of done**
The API endpoint `/generate?count=100` can be called and will generate 100 randomized measurements, and save them to the database.

**Comment by NeoAren** [comment]
closed by #28
