### ISSUE TITLE
Deploy operator app to Vercel

### ISSUE THREAD

**Issue by NeoAren** [tamaskr/crowdsourced-network-metrics#56]
Try to deploy the operator app (which is a next.js app) to the vercel platform so that it can be accessed remotely and not just on the local machine. Some useful links:
https://nextjs.org/learn/basics/deploying-nextjs-app/platform-details
https://vercel.com/docs/concepts/git/vercel-for-github

**Definition of done**
Operator app can be deployed to Vercel and accessed from there.

**Comment by tamaskr** [comment]
Deployment done
[https://crowdsourced-network-metrics-plum.vercel.app/](https://crowdsourced-network-metrics-plum.vercel.app/)
