### ISSUE TITLE
[Operator app] Display all queries on the Home page as clickable links

### ISSUE THREAD

**Issue by tamaskr** [tamaskr/crowdsourced-network-metrics#75]
- When the Home page of the operator app is opened, all of the measurements should be fetched automatically from `/measurements` endpoint
- The measurements should be grouped by query id and displayed in a list (for example, if we have 4 measurements with the same query id, we should just display that query id in the list)
- When an item in the list is clicked, the user should be redirected to the query's details page (the `href` can be for example `/details?id={queryId}`) - then, the query details should be fetched from [this endpoint](https://github.com/tamaskr/crowdsourced-network-metrics/issues/68) 

**Hints**
- React-query has a [useQuery](https://tanstack.com/query/v4/docs/reference/useQuery?from=reactQueryV3&original=https://react-query-v3.tanstack.com/reference/useQuery) hook, which can be used to fetch data - it can just be copied from [here](https://github.com/tamaskr/crowdsourced-network-metrics/blob/main/packages/operator-app/src/pages/statistics/index.tsx)
- Next.js has a built-in [Link](https://nextjs.org/docs/api-reference/next/link) component that can be used for navigation (we're already using that in the `navBar`)

**Definition of done**
- When the user opens the Home page of the operator app, all the queries are displayed in a list - after clicking any of the queries, the user will be redirected to a page where that query's details will be fetched

**Comment by NeoAren** [comment]
closed by #84
